# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calls.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1294, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1294, 680))
        MainWindow.setMaximumSize(QtCore.QSize(1294, 680))
        MainWindow.setStyleSheet("font: 12pt \"Segoe MDL2 Assets\";")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.main_widget.setEnabled(False)
        self.main_widget.setGeometry(QtCore.QRect(2, 1, 1290, 645))
        self.main_widget.setAutoFillBackground(False)
        self.main_widget.setStyleSheet("")
        self.main_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.main_widget.setTabsClosable(False)
        self.main_widget.setMovable(False)
        self.main_widget.setTabBarAutoHide(False)
        self.main_widget.setObjectName("main_widget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.connections_widget = QtWidgets.QTabWidget(self.tab_5)
        self.connections_widget.setGeometry(QtCore.QRect(50, 10, 1031, 590))
        self.connections_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.connections_widget.setObjectName("connections_widget")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.port_no_server_msg = QtWidgets.QLineEdit(self.tab_8)
        self.port_no_server_msg.setGeometry(QtCore.QRect(660, 222, 170, 30))
        self.port_no_server_msg.setObjectName("port_no_server_msg")
        self.start_all_button = QtWidgets.QPushButton(self.tab_8)
        self.start_all_button.setGeometry(QtCore.QRect(385, 350, 271, 28))
        self.start_all_button.setObjectName("start_all_button")
        self.label_28 = QtWidgets.QLabel(self.tab_8)
        self.label_28.setGeometry(QtCore.QRect(608, 224, 51, 21))
        self.label_28.setObjectName("label_28")
        self.ip_add_server_video = QtWidgets.QLineEdit(self.tab_8)
        self.ip_add_server_video.setGeometry(QtCore.QRect(306, 293, 291, 30))
        self.ip_add_server_video.setText("")
        self.ip_add_server_video.setObjectName("ip_add_server_video")
        self.port_no_server_video = QtWidgets.QLineEdit(self.tab_8)
        self.port_no_server_video.setGeometry(QtCore.QRect(660, 293, 170, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_no_server_video.sizePolicy().hasHeightForWidth())
        self.port_no_server_video.setSizePolicy(sizePolicy)
        self.port_no_server_video.setCursorPosition(40)
        self.port_no_server_video.setObjectName("port_no_server_video")
        self.label_29 = QtWidgets.QLabel(self.tab_8)
        self.label_29.setGeometry(QtCore.QRect(30, 296, 151, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_8)
        self.label_30.setGeometry(QtCore.QRect(211, 261, 91, 16))
        self.label_30.setObjectName("label_30")
        self.start_button_audio = QtWidgets.QPushButton(self.tab_8)
        self.start_button_audio.setGeometry(QtCore.QRect(840, 255, 153, 28))
        self.start_button_audio.setObjectName("start_button_audio")
        self.label_31 = QtWidgets.QLabel(self.tab_8)
        self.label_31.setGeometry(QtCore.QRect(607, 301, 51, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_8)
        self.label_32.setGeometry(QtCore.QRect(29, 225, 151, 16))
        self.label_32.setObjectName("label_32")
        self.ip_add_server_audio = QtWidgets.QLineEdit(self.tab_8)
        self.ip_add_server_audio.setGeometry(QtCore.QRect(306, 258, 291, 30))
        self.ip_add_server_audio.setText("")
        self.ip_add_server_audio.setObjectName("ip_add_server_audio")
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(608, 264, 51, 16))
        self.label_33.setObjectName("label_33")
        self.clear_fields_server = QtWidgets.QPushButton(self.tab_8)
        self.clear_fields_server.setGeometry(QtCore.QRect(442, 386, 150, 28))
        self.clear_fields_server.setObjectName("clear_fields_server")
        self.label_34 = QtWidgets.QLabel(self.tab_8)
        self.label_34.setGeometry(QtCore.QRect(30, 261, 151, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_8)
        self.label_35.setGeometry(QtCore.QRect(212, 225, 91, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_8)
        self.label_36.setGeometry(QtCore.QRect(211, 296, 91, 16))
        self.label_36.setObjectName("label_36")
        self.port_no_server_audio = QtWidgets.QLineEdit(self.tab_8)
        self.port_no_server_audio.setGeometry(QtCore.QRect(660, 257, 170, 30))
        self.port_no_server_audio.setObjectName("port_no_server_audio")
        self.ip_add_server_msg = QtWidgets.QLineEdit(self.tab_8)
        self.ip_add_server_msg.setGeometry(QtCore.QRect(307, 222, 291, 30))
        self.ip_add_server_msg.setText("")
        self.ip_add_server_msg.setObjectName("ip_add_server_msg")
        self.start_button_video = QtWidgets.QPushButton(self.tab_8)
        self.start_button_video.setGeometry(QtCore.QRect(840, 292, 151, 28))
        self.start_button_video.setObjectName("start_button_video")
        self.start_button_msg = QtWidgets.QPushButton(self.tab_8)
        self.start_button_msg.setGeometry(QtCore.QRect(840, 220, 151, 28))
        self.start_button_msg.setObjectName("start_button_msg")
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setGeometry(QtCore.QRect(370, 31, 281, 50))
        self.label_14.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_14.setObjectName("label_14")
        self.label_49 = QtWidgets.QLabel(self.tab_8)
        self.label_49.setGeometry(QtCore.QRect(184, 81, 741, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_8)
        self.label_50.setGeometry(QtCore.QRect(240, 105, 571, 20))
        self.label_50.setStyleSheet("font: 10pt \"Segoe MDL2 Assets\";")
        self.label_50.setObjectName("label_50")
        self.connections_widget.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.ip_add_msg = QtWidgets.QLineEdit(self.tab_6)
        self.ip_add_msg.setGeometry(QtCore.QRect(307, 222, 291, 30))
        self.ip_add_msg.setText("")
        self.ip_add_msg.setObjectName("ip_add_msg")
        self.port_no_msg = QtWidgets.QLineEdit(self.tab_6)
        self.port_no_msg.setGeometry(QtCore.QRect(660, 222, 170, 30))
        self.port_no_msg.setObjectName("port_no_msg")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(212, 225, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(608, 224, 51, 21))
        self.label_5.setObjectName("label_5")
        self.connect_all_button = QtWidgets.QPushButton(self.tab_6)
        self.connect_all_button.setGeometry(QtCore.QRect(385, 350, 271, 28))
        self.connect_all_button.setObjectName("connect_all_button")
        self.clear_fields_client = QtWidgets.QPushButton(self.tab_6)
        self.clear_fields_client.setGeometry(QtCore.QRect(442, 386, 150, 28))
        self.clear_fields_client.setObjectName("clear_fields_client")
        self.port_no_audio = QtWidgets.QLineEdit(self.tab_6)
        self.port_no_audio.setGeometry(QtCore.QRect(660, 257, 170, 30))
        self.port_no_audio.setObjectName("port_no_audio")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(608, 264, 51, 16))
        self.label_10.setObjectName("label_10")
        self.port_no_video = QtWidgets.QLineEdit(self.tab_6)
        self.port_no_video.setGeometry(QtCore.QRect(660, 293, 170, 30))
        self.port_no_video.setCursorPosition(0)
        self.port_no_video.setObjectName("port_no_video")
        self.label_11 = QtWidgets.QLabel(self.tab_6)
        self.label_11.setGeometry(QtCore.QRect(607, 301, 51, 16))
        self.label_11.setObjectName("label_11")
        self.ip_add_audio = QtWidgets.QLineEdit(self.tab_6)
        self.ip_add_audio.setGeometry(QtCore.QRect(306, 258, 291, 30))
        self.ip_add_audio.setText("")
        self.ip_add_audio.setObjectName("ip_add_audio")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(211, 261, 91, 16))
        self.label_12.setObjectName("label_12")
        self.ip_add_video = QtWidgets.QLineEdit(self.tab_6)
        self.ip_add_video.setGeometry(QtCore.QRect(306, 293, 291, 30))
        self.ip_add_video.setText("")
        self.ip_add_video.setObjectName("ip_add_video")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(211, 296, 91, 16))
        self.label_18.setObjectName("label_18")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(30, 261, 151, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(29, 225, 151, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(30, 296, 151, 20))
        self.label_27.setObjectName("label_27")
        self.connect_button_msg = QtWidgets.QPushButton(self.tab_6)
        self.connect_button_msg.setGeometry(QtCore.QRect(840, 220, 151, 30))
        self.connect_button_msg.setObjectName("connect_button_msg")
        self.connect_button_audio = QtWidgets.QPushButton(self.tab_6)
        self.connect_button_audio.setGeometry(QtCore.QRect(840, 255, 153, 30))
        self.connect_button_audio.setObjectName("connect_button_audio")
        self.connect_button_video = QtWidgets.QPushButton(self.tab_6)
        self.connect_button_video.setGeometry(QtCore.QRect(840, 292, 151, 30))
        self.connect_button_video.setObjectName("connect_button_video")
        self.label_146 = QtWidgets.QLabel(self.tab_6)
        self.label_146.setGeometry(QtCore.QRect(220, 80, 741, 20))
        self.label_146.setObjectName("label_146")
        self.label_147 = QtWidgets.QLabel(self.tab_6)
        self.label_147.setGeometry(QtCore.QRect(370, 31, 281, 50))
        self.label_147.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_147.setObjectName("label_147")
        self.label_148 = QtWidgets.QLabel(self.tab_6)
        self.label_148.setGeometry(QtCore.QRect(180, 103, 701, 20))
        self.label_148.setStyleSheet("font: 10pt \"Segoe MDL2 Assets\";")
        self.label_148.setObjectName("label_148")
        self.connections_widget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_58 = QtWidgets.QLabel(self.tab_7)
        self.label_58.setGeometry(QtCore.QRect(370, 31, 331, 50))
        self.label_58.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_7)
        self.label_59.setGeometry(QtCore.QRect(152, 80, 810, 20))
        self.label_59.setObjectName("label_59")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(84, 149, 191, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(440, 150, 191, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(769, 150, 191, 20))
        self.label_3.setObjectName("label_3")
        self.connected_msg = QtWidgets.QListWidget(self.tab_7)
        self.connected_msg.setGeometry(QtCore.QRect(20, 180, 311, 360))
        self.connected_msg.setObjectName("connected_msg")
        self.connected_audio = QtWidgets.QListWidget(self.tab_7)
        self.connected_audio.setGeometry(QtCore.QRect(356, 180, 311, 360))
        self.connected_audio.setObjectName("connected_audio")
        self.connected_video = QtWidgets.QListWidget(self.tab_7)
        self.connected_video.setGeometry(QtCore.QRect(691, 180, 311, 360))
        self.connected_video.setObjectName("connected_video")
        self.connections_widget.addTab(self.tab_7, "")
        self.main_widget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.msg_area = QtWidgets.QPlainTextEdit(self.tab)
        self.msg_area.setGeometry(QtCore.QRect(825, 265, 444, 91))
        self.msg_area.setObjectName("msg_area")
        self.send_button = QtWidgets.QPushButton(self.tab)
        self.send_button.setGeometry(QtCore.QRect(825, 365, 444, 31))
        self.send_button.setObjectName("send_button")
        self.wipe_button = QtWidgets.QPushButton(self.tab)
        self.wipe_button.setGeometry(QtCore.QRect(826, 404, 140, 30))
        self.wipe_button.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.wipe_button.setObjectName("wipe_button")
        self.label_86 = QtWidgets.QLabel(self.tab)
        self.label_86.setGeometry(QtCore.QRect(480, 54, 121, 31))
        self.label_86.setObjectName("label_86")
        self.running_on = QtWidgets.QLabel(self.tab)
        self.running_on.setGeometry(QtCore.QRect(604, 54, 221, 31))
        self.running_on.setObjectName("running_on")
        self.message_box = QtWidgets.QListWidget(self.tab)
        self.message_box.setGeometry(QtCore.QRect(13, 85, 800, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_box.sizePolicy().hasHeightForWidth())
        self.message_box.setSizePolicy(sizePolicy)
        self.message_box.setFrameShape(QtWidgets.QFrame.Box)
        self.message_box.setFrameShadow(QtWidgets.QFrame.Plain)
        self.message_box.setLineWidth(3)
        self.message_box.setAutoScroll(True)
        self.message_box.setViewMode(QtWidgets.QListView.ListMode)
        self.message_box.setObjectName("message_box")
        self.clear_messages_button = QtWidgets.QPushButton(self.tab)
        self.clear_messages_button.setGeometry(QtCore.QRect(977, 404, 140, 30))
        self.clear_messages_button.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.clear_messages_button.setObjectName("clear_messages_button")
        self.leave_chat_button = QtWidgets.QPushButton(self.tab)
        self.leave_chat_button.setGeometry(QtCore.QRect(1126, 403, 140, 30))
        self.leave_chat_button.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.leave_chat_button.setObjectName("leave_chat_button")
        self.label_56 = QtWidgets.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(353, -4, 581, 40))
        self.label_56.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab)
        self.label_57.setGeometry(QtCore.QRect(226, 39, 840, 20))
        self.label_57.setObjectName("label_57")
        self.main_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("")
        self.tab_2.setObjectName("tab_2")
        self.calls_widget = QtWidgets.QTabWidget(self.tab_2)
        self.calls_widget.setGeometry(QtCore.QRect(10, 2, 1271, 615))
        self.calls_widget.setStyleSheet("")
        self.calls_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.calls_widget.setObjectName("calls_widget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("")
        self.tab_3.setObjectName("tab_3")
        self.visualization = QtWidgets.QLabel(self.tab_3)
        self.visualization.setGeometry(QtCore.QRect(280, 142, 641, 380))
        self.visualization.setText("")
        self.visualization.setAlignment(QtCore.Qt.AlignCenter)
        self.visualization.setObjectName("visualization")
        self.leave_audio_button = QtWidgets.QPushButton(self.tab_3)
        self.leave_audio_button.setGeometry(QtCore.QRect(493, 525, 241, 41))
        self.leave_audio_button.setObjectName("leave_audio_button")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(507, 571, 111, 16))
        self.label_17.setObjectName("label_17")
        self.status = QtWidgets.QLabel(self.tab_3)
        self.status.setGeometry(QtCore.QRect(615, 563, 201, 30))
        self.status.setObjectName("status")
        self.timer = QtWidgets.QLabel(self.tab_3)
        self.timer.setGeometry(QtCore.QRect(572, 300, 101, 40))
        self.timer.setStyleSheet("font: 16pt \"Segoe MDL2 Assets\";")
        self.timer.setObjectName("timer")
        self.label_52 = QtWidgets.QLabel(self.tab_3)
        self.label_52.setGeometry(QtCore.QRect(446, 40, 391, 40))
        self.label_52.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_52.setObjectName("label_52")
        self.label_51 = QtWidgets.QLabel(self.tab_3)
        self.label_51.setGeometry(QtCore.QRect(186, 90, 880, 20))
        self.label_51.setObjectName("label_51")
        self.running_on_audio = QtWidgets.QLabel(self.tab_3)
        self.running_on_audio.setGeometry(QtCore.QRect(589, 107, 221, 40))
        self.running_on_audio.setObjectName("running_on_audio")
        self.label_87 = QtWidgets.QLabel(self.tab_3)
        self.label_87.setGeometry(QtCore.QRect(474, 105, 121, 40))
        self.label_87.setObjectName("label_87")
        self.calls_widget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("")
        self.tab_4.setObjectName("tab_4")
        self.leave_video_button = QtWidgets.QPushButton(self.tab_4)
        self.leave_video_button.setGeometry(QtCore.QRect(1011, 549, 241, 40))
        self.leave_video_button.setObjectName("leave_video_button")
        self.video_feed = QtWidgets.QLabel(self.tab_4)
        self.video_feed.setGeometry(QtCore.QRect(10, 3, 1245, 544))
        self.video_feed.setFrameShape(QtWidgets.QFrame.Box)
        self.video_feed.setText("")
        self.video_feed.setTextFormat(QtCore.Qt.PlainText)
        self.video_feed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.video_feed.setObjectName("video_feed")
        self.label_53 = QtWidgets.QLabel(self.tab_4)
        self.label_53.setGeometry(QtCore.QRect(10, 549, 391, 40))
        self.label_53.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_4)
        self.label_54.setGeometry(QtCore.QRect(480, 550, 451, 21))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_4)
        self.label_55.setGeometry(QtCore.QRect(440, 566, 321, 21))
        self.label_55.setStyleSheet("font: 75 italic 9pt \"Sitka Display\";")
        self.label_55.setObjectName("label_55")
        self.label_88 = QtWidgets.QLabel(self.tab_4)
        self.label_88.setGeometry(QtCore.QRect(761, 567, 110, 20))
        self.label_88.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.label_88.setObjectName("label_88")
        self.running_on_video = QtWidgets.QLabel(self.tab_4)
        self.running_on_video.setGeometry(QtCore.QRect(870, 566, 151, 21))
        self.running_on_video.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";")
        self.running_on_video.setObjectName("running_on_video")
        self.video_feed.raise_()
        self.leave_video_button.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_88.raise_()
        self.running_on_video.raise_()
        self.calls_widget.addTab(self.tab_4, "")
        self.main_widget.addTab(self.tab_2, "")
        self.first_frame = QtWidgets.QFrame(self.centralwidget)
        self.first_frame.setEnabled(True)
        self.first_frame.setGeometry(QtCore.QRect(359, 94, 572, 410))
        self.first_frame.setAutoFillBackground(False)
        self.first_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.first_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.first_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.first_frame.setLineWidth(2)
        self.first_frame.setObjectName("first_frame")
        self.proceed_button = QtWidgets.QPushButton(self.first_frame)
        self.proceed_button.setEnabled(True)
        self.proceed_button.setGeometry(QtCore.QRect(210, 364, 181, 30))
        self.proceed_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proceed_button.setAutoFillBackground(False)
        self.proceed_button.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"color: rgb(0, 0, 0);")
        self.proceed_button.setAutoDefault(True)
        self.proceed_button.setDefault(True)
        self.proceed_button.setFlat(False)
        self.proceed_button.setObjectName("proceed_button")
        self.label_6 = QtWidgets.QLabel(self.first_frame)
        self.label_6.setGeometry(QtCore.QRect(233, 26, 245, 70))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 22pt \"MV Boli\";")
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.first_frame)
        self.label_13.setGeometry(QtCore.QRect(100, 90, 421, 41))
        self.label_13.setObjectName("label_13")
        self.name_info = QtWidgets.QLabel(self.first_frame)
        self.name_info.setGeometry(QtCore.QRect(190, 145, 171, 30))
        self.name_info.setObjectName("name_info")
        self.network_label = QtWidgets.QLabel(self.first_frame)
        self.network_label.setGeometry(QtCore.QRect(6, 234, 560, 20))
        self.network_label.setAlignment(QtCore.Qt.AlignCenter)
        self.network_label.setObjectName("network_label")
        self.name_input = QtWidgets.QLineEdit(self.first_frame)
        self.name_input.setEnabled(True)
        self.name_input.setGeometry(QtCore.QRect(100, 180, 370, 31))
        self.name_input.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input.setClearButtonEnabled(True)
        self.name_input.setObjectName("name_input")
        self.power_button = QtWidgets.QPushButton(self.first_frame)
        self.power_button.setGeometry(QtCore.QRect(518, 356, 50, 50))
        self.power_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.power_button.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 22pt \"Segoe MDL2 Assets\";")
        self.power_button.setAutoDefault(True)
        self.power_button.setDefault(False)
        self.power_button.setFlat(True)
        self.power_button.setObjectName("power_button")
        self.ip_input = QtWidgets.QLineEdit(self.first_frame)
        self.ip_input.setGeometry(QtCore.QRect(100, 258, 370, 30))
        self.ip_input.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_input.setClearButtonEnabled(True)
        self.ip_input.setObjectName("ip_input")
        self.label_16 = QtWidgets.QLabel(self.first_frame)
        self.label_16.setGeometry(QtCore.QRect(93, 292, 410, 20))
        self.label_16.setStyleSheet("font: 75 italic 9pt \"Sitka Display\";")
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.first_frame)
        self.label_19.setGeometry(QtCore.QRect(99, 309, 401, 20))
        self.label_19.setStyleSheet("font: 75 italic 9pt \"Sitka Display\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.first_frame)
        self.label_20.setGeometry(QtCore.QRect(98, 326, 401, 20))
        self.label_20.setStyleSheet("font: 75 italic 9pt \"Sitka Display\";")
        self.label_20.setObjectName("label_20")
        self.label_7 = QtWidgets.QLabel(self.first_frame)
        self.label_7.setGeometry(QtCore.QRect(96, 8, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 75 italic 16pt \"Sitka Display\";")
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.first_frame)
        self.line.setGeometry(QtCore.QRect(3, 93, 566, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.proceed_button.raise_()
        self.label_13.raise_()
        self.label_6.raise_()
        self.name_info.raise_()
        self.network_label.raise_()
        self.name_input.raise_()
        self.power_button.raise_()
        self.ip_input.raise_()
        self.label_16.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_7.raise_()
        self.line.raise_()
        self.about_developer = QtWidgets.QFrame(self.centralwidget)
        self.about_developer.setEnabled(True)
        self.about_developer.setGeometry(QtCore.QRect(-2, 28, 1300, 680))
        self.about_developer.setAutoFillBackground(False)
        self.about_developer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.about_developer.setFrameShape(QtWidgets.QFrame.Box)
        self.about_developer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.about_developer.setLineWidth(2)
        self.about_developer.setObjectName("about_developer")
        self.label_8 = QtWidgets.QLabel(self.about_developer)
        self.label_8.setGeometry(QtCore.QRect(519, 40, 240, 40))
        self.label_8.setStyleSheet("text-decoration: underline;\n"
"font: 20pt \"Segoe MDL2 Assets\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.about_developer)
        self.label_9.setGeometry(QtCore.QRect(40, 120, 651, 30))
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.about_developer)
        self.label_15.setGeometry(QtCore.QRect(40, 153, 1241, 30))
        self.label_15.setObjectName("label_15")
        self.close_button_dev = QtWidgets.QPushButton(self.about_developer)
        self.close_button_dev.setEnabled(True)
        self.close_button_dev.setGeometry(QtCore.QRect(550, 557, 181, 30))
        self.close_button_dev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_button_dev.setAutoFillBackground(False)
        self.close_button_dev.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"color: rgb(0, 0, 0);")
        self.close_button_dev.setAutoDefault(True)
        self.close_button_dev.setDefault(True)
        self.close_button_dev.setFlat(False)
        self.close_button_dev.setObjectName("close_button_dev")
        self.label_21 = QtWidgets.QLabel(self.about_developer)
        self.label_21.setGeometry(QtCore.QRect(40, 190, 1241, 30))
        self.label_21.setObjectName("label_21")
        self.about_software = QtWidgets.QFrame(self.centralwidget)
        self.about_software.setEnabled(True)
        self.about_software.setGeometry(QtCore.QRect(-3, -10, 1300, 680))
        self.about_software.setAutoFillBackground(False)
        self.about_software.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.about_software.setFrameShape(QtWidgets.QFrame.Box)
        self.about_software.setFrameShadow(QtWidgets.QFrame.Plain)
        self.about_software.setLineWidth(2)
        self.about_software.setObjectName("about_software")
        self.label_22 = QtWidgets.QLabel(self.about_software)
        self.label_22.setGeometry(QtCore.QRect(519, 40, 240, 40))
        self.label_22.setStyleSheet("text-decoration: underline;\n"
"font: 20pt \"Segoe MDL2 Assets\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.about_software)
        self.label_23.setGeometry(QtCore.QRect(40, 120, 921, 30))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.about_software)
        self.label_24.setGeometry(QtCore.QRect(40, 153, 1241, 30))
        self.label_24.setObjectName("label_24")
        self.close_button_soft = QtWidgets.QPushButton(self.about_software)
        self.close_button_soft.setEnabled(True)
        self.close_button_soft.setGeometry(QtCore.QRect(550, 581, 181, 30))
        self.close_button_soft.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_button_soft.setAutoFillBackground(False)
        self.close_button_soft.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"color: rgb(0, 0, 0);")
        self.close_button_soft.setAutoDefault(True)
        self.close_button_soft.setDefault(True)
        self.close_button_soft.setFlat(False)
        self.close_button_soft.setObjectName("close_button_soft")
        self.label_37 = QtWidgets.QLabel(self.about_software)
        self.label_37.setGeometry(QtCore.QRect(40, 186, 1241, 30))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.about_software)
        self.label_38.setGeometry(QtCore.QRect(41, 220, 1241, 30))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.about_software)
        self.label_39.setGeometry(QtCore.QRect(41, 254, 1241, 30))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.about_software)
        self.label_40.setGeometry(QtCore.QRect(40, 287, 1241, 30))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.about_software)
        self.label_41.setGeometry(QtCore.QRect(60, 313, 551, 30))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.about_software)
        self.label_42.setGeometry(QtCore.QRect(41, 346, 551, 30))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.about_software)
        self.label_43.setGeometry(QtCore.QRect(332, 400, 620, 30))
        self.label_43.setStyleSheet("font: 18pt \"Segoe MDL2 Assets\";\n"
"text-decoration: underline;")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.about_software)
        self.label_44.setGeometry(QtCore.QRect(510, 430, 231, 30))
        self.label_44.setStyleSheet("font: italic 8pt \"Cambria\";\n"
"text-decoration: underline;")
        self.label_44.setObjectName("label_44")
        self.about_software.raise_()
        self.about_developer.raise_()
        self.main_widget.raise_()
        self.first_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1294, 30))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.exit_menu = QtWidgets.QMenu(self.menubar)
        self.exit_menu.setObjectName("exit_menu")
        MainWindow.setMenuBar(self.menubar)
        self.about_dev = QtWidgets.QAction(MainWindow)
        self.about_dev.setCheckable(False)
        self.about_dev.setShortcutVisibleInContextMenu(False)
        self.about_dev.setObjectName("about_dev")
        self.about_soft = QtWidgets.QAction(MainWindow)
        self.about_soft.setObjectName("about_soft")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuAbout.addAction(self.about_dev)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.about_soft)
        self.menuAbout.addSeparator()
        self.exit_menu.addAction(self.actionExit)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.exit_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.main_widget.setCurrentIndex(0)
        self.connections_widget.setCurrentIndex(0)
        self.calls_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.port_no_server_msg.setText(_translate("MainWindow", "2000"))
        self.start_all_button.setText(_translate("MainWindow", "START ALL SERVERS"))
        self.label_28.setText(_translate("MainWindow", "Port :"))
        self.port_no_server_video.setText(_translate("MainWindow", "4000 , 5000 , 6000 , 7000 , 8000 , 10000"))
        self.label_29.setText(_translate("MainWindow", "VIDEO CALLS  ->"))
        self.label_30.setText(_translate("MainWindow", "IP ADD. :"))
        self.start_button_audio.setText(_translate("MainWindow", "START..."))
        self.label_31.setText(_translate("MainWindow", "Port :"))
        self.label_32.setText(_translate("MainWindow", "MESSAGING     ->"))
        self.label_33.setText(_translate("MainWindow", "Port :"))
        self.clear_fields_server.setText(_translate("MainWindow", "Clear All Fields"))
        self.label_34.setText(_translate("MainWindow", "AUDIO CALLS  ->"))
        self.label_35.setText(_translate("MainWindow", "IP ADD. :"))
        self.label_36.setText(_translate("MainWindow", "IP ADD. :"))
        self.port_no_server_audio.setText(_translate("MainWindow", "3000"))
        self.start_button_video.setText(_translate("MainWindow", "START..."))
        self.start_button_msg.setText(_translate("MainWindow", "START..."))
        self.label_14.setText(_translate("MainWindow", "MANAGE SERVERS"))
        self.label_49.setText(_translate("MainWindow", "YOU CAN START SERVERS HERE, TO PROVIDE ACCESS TO NEW CONNECTIONS"))
        self.label_50.setText(_translate("MainWindow", "NOTE : PROVIDE SAME IP ADDRESS AND PORT NUMBER ON CLIENT SIDE"))
        self.connections_widget.setTabText(self.connections_widget.indexOf(self.tab_8), _translate("MainWindow", "SERVERS.."))
        self.port_no_msg.setText(_translate("MainWindow", "2000"))
        self.label_4.setText(_translate("MainWindow", "IP ADD. :"))
        self.label_5.setText(_translate("MainWindow", "Port :"))
        self.connect_all_button.setText(_translate("MainWindow", "CONNECT ALL CLIENTS"))
        self.clear_fields_client.setText(_translate("MainWindow", "Clear All Fields"))
        self.port_no_audio.setText(_translate("MainWindow", "3000"))
        self.label_10.setText(_translate("MainWindow", "Port :"))
        self.port_no_video.setText(_translate("MainWindow", "5000 , 6000 , 7000 , 8000 , 9000 , 10000"))
        self.label_11.setText(_translate("MainWindow", "Port :"))
        self.label_12.setText(_translate("MainWindow", "IP ADD. :"))
        self.label_18.setText(_translate("MainWindow", "IP ADD. :"))
        self.label_25.setText(_translate("MainWindow", "AUDIO CALLS  ->"))
        self.label_26.setText(_translate("MainWindow", "MESSAGING     ->"))
        self.label_27.setText(_translate("MainWindow", "VIDEO CALLS  ->"))
        self.connect_button_msg.setText(_translate("MainWindow", "CONNECT..."))
        self.connect_button_audio.setText(_translate("MainWindow", "CONNECT..."))
        self.connect_button_video.setText(_translate("MainWindow", "CONNECT..."))
        self.label_146.setText(_translate("MainWindow", "YOU CAN CONNECT AS A CLIENT TO SPECIFIC SERVERS FROM HERE"))
        self.label_147.setText(_translate("MainWindow", "MANAGE CLIENTS"))
        self.label_148.setText(_translate("MainWindow", "NOTE : PROVIDE SAME IP ADDRESS AND PORT NUMBER ON WHICH SERVER IS RUNNING"))
        self.connections_widget.setTabText(self.connections_widget.indexOf(self.tab_6), _translate("MainWindow", "CONNECT TO.."))
        self.label_58.setText(_translate("MainWindow", "CONNECTED DEVICES"))
        self.label_59.setText(_translate("MainWindow", "LIST OF IPS OF ALL CONNECTED DEVICES TO BE SHOWN HERE (ON YOUR SERVERS ONLY)"))
        self.label.setText(_translate("MainWindow", "MESSAGING SERVER"))
        self.label_2.setText(_translate("MainWindow", "AUDIO SERVER"))
        self.label_3.setText(_translate("MainWindow", "VIDEO SERVER"))
        self.connections_widget.setTabText(self.connections_widget.indexOf(self.tab_7), _translate("MainWindow", "CONNECTED TO.."))
        self.main_widget.setTabText(self.main_widget.indexOf(self.tab_5), _translate("MainWindow", "CONNECTIONS..."))
        self.msg_area.setPlaceholderText(_translate("MainWindow", "Write Message Here..."))
        self.send_button.setText(_translate("MainWindow", "Send Message..."))
        self.wipe_button.setText(_translate("MainWindow", "Wipe Message Field"))
        self.label_86.setText(_translate("MainWindow", "Running On :"))
        self.running_on.setText(_translate("MainWindow", "NULL YET..."))
        self.clear_messages_button.setText(_translate("MainWindow", "Clear All Messages"))
        self.leave_chat_button.setText(_translate("MainWindow", "Leave Chat Room"))
        self.label_56.setText(_translate("MainWindow", "CONFERENCE MESSAGING CHAT ROOM"))
        self.label_57.setText(_translate("MainWindow", "SEND AND RECEIVE TEXT MESSAGES FROM DEVICES CONNECTED TO SAME MESSAGING SERVER"))
        self.main_widget.setTabText(self.main_widget.indexOf(self.tab), _translate("MainWindow", "MESSAGING..."))
        self.leave_audio_button.setText(_translate("MainWindow", "LEAVE CONFERENCE"))
        self.label_17.setText(_translate("MainWindow", "MIC Status : "))
        self.status.setText(_translate("MainWindow", "none"))
        self.timer.setText(_translate("MainWindow", "0:0:0"))
        self.label_52.setText(_translate("MainWindow", "AUDIO CONFERENCE CALL"))
        self.label_51.setText(_translate("MainWindow", "ALL DEVICES CONNECTED TO SAME AUDIO SERVER SHALL BE ABLE TO HEAR YOU AND VISEVERSA"))
        self.running_on_audio.setText(_translate("MainWindow", "NULL YET..."))
        self.label_87.setText(_translate("MainWindow", "Running On :"))
        self.calls_widget.setTabText(self.calls_widget.indexOf(self.tab_3), _translate("MainWindow", "AUDIO CALLS.."))
        self.leave_video_button.setText(_translate("MainWindow", "LEAVE CONFERENCE"))
        self.label_53.setText(_translate("MainWindow", "VIDEO CONFERENCE CALL"))
        self.label_54.setText(_translate("MainWindow", "CONNECTS UP TO 4 DEVICES SIMULTANEOUSLY"))
        self.label_55.setText(_translate("MainWindow", "Devices Connected On Same Server Can Connect You."))
        self.label_88.setText(_translate("MainWindow", "{Running On IP :"))
        self.running_on_video.setText(_translate("MainWindow", "NULL YET...}"))
        self.calls_widget.setTabText(self.calls_widget.indexOf(self.tab_4), _translate("MainWindow", "VIDEO CALLS.."))
        self.main_widget.setTabText(self.main_widget.indexOf(self.tab_2), _translate("MainWindow", "CALLS..."))
        self.proceed_button.setText(_translate("MainWindow", "Proceed..."))
        self.proceed_button.setShortcut(_translate("MainWindow", "Return"))
        self.label_6.setText(_translate("MainWindow", "TheConference"))
        self.label_13.setText(_translate("MainWindow", "Please provide bellow details to proceed..."))
        self.name_info.setText(_translate("MainWindow", "Your Good Name : "))
        self.network_label.setText(_translate("MainWindow", "IP Of Your Network : "))
        self.name_input.setPlaceholderText(_translate("MainWindow", "Enter Your Name Here..."))
        self.power_button.setText(_translate("MainWindow", ""))
        self.ip_input.setPlaceholderText(_translate("MainWindow", "i.e 127.0.0.1"))
        self.label_16.setText(_translate("MainWindow", "NOTE: THIS IS AUTOMATIC IP SELECTION SYSTEM PERFORMED"))
        self.label_19.setText(_translate("MainWindow", "BY THIS SOFTWARE ON THE BASIS OF FIRST AND STRONG CO-"))
        self.label_20.setText(_translate("MainWindow", "-NNECTION, YOU CAN CHANGE IT TO YOUR PREFERRED ONE..."))
        self.label_7.setText(_translate("MainWindow", "Welcome To"))
        self.label_8.setText(_translate("MainWindow", "About Developer"))
        self.label_9.setText(_translate("MainWindow", "This Software has been developed by \"SALEEM ABDULLAH BOZDAR\""))
        self.label_15.setText(_translate("MainWindow", "I (developer) am a student of Computer Science @ Institute of Mathematics and Computer Science, University of Sindh, Sindh, Jamshoro"))
        self.close_button_dev.setText(_translate("MainWindow", "Close..."))
        self.label_21.setText(_translate("MainWindow", "One Can contact me for Projects, Bug fixes, or any other Info @ \'saleembozdar1@gmail.com\'"))
        self.label_22.setText(_translate("MainWindow", "About Software"))
        self.label_23.setText(_translate("MainWindow", "->This Software is an Package of Text Messenger, Audio Calls and Video Calls (All In Conference Mode)"))
        self.label_24.setText(_translate("MainWindow", "->This Package has been developed for Special Purposes and one needs Permission from Developer to use it"))
        self.close_button_soft.setText(_translate("MainWindow", "Close..."))
        self.label_37.setText(_translate("MainWindow", "->This is very Basic and Trial Version so may have Bugs or Performance issues"))
        self.label_38.setText(_translate("MainWindow", "->Bugs and Other Issues and be discussed With Developer by sending Email @ \'saleembozdar1@gmail.com\'"))
        self.label_39.setText(_translate("MainWindow", "->Developer keeps allrights of copyright of this software and has right for releasing next version of this software"))
        self.label_40.setText(_translate("MainWindow", "->Though this software has developed for secure connection purposes with aim as your data security as the first priority but still developer"))
        self.label_41.setText(_translate("MainWindow", " shall not be responsible for any data loss or illegal use of data."))
        self.label_42.setText(_translate("MainWindow", "-> Hopes for the best... --Thank You.."))
        self.label_43.setText(_translate("MainWindow", "TheConference V1.0 released on July/4th/2019"))
        self.label_44.setText(_translate("MainWindow", "Note: New Version Shall be releases soon"))
        self.menuAbout.setTitle(_translate("MainWindow", "About..."))
        self.exit_menu.setTitle(_translate("MainWindow", "Exit..."))
        self.about_dev.setText(_translate("MainWindow", "About Developer"))
        self.about_soft.setText(_translate("MainWindow", "About Software"))
        self.actionExit.setText(_translate("MainWindow", "Exit..!"))
